[2025-02-06T11:39:20.945+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-06T11:39:20.960+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_news.extract_and_save_task manual__2025-02-06T11:39:18.448534+00:00 [queued]>
[2025-02-06T11:39:20.968+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_news.extract_and_save_task manual__2025-02-06T11:39:18.448534+00:00 [queued]>
[2025-02-06T11:39:20.969+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-06T11:39:20.981+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_and_save_task> on 2025-02-06 11:39:18.448534+00:00
[2025-02-06T11:39:20.987+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=77) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-06T11:39:20.988+0000] {standard_task_runner.py:72} INFO - Started process 79 to run task
[2025-02-06T11:39:20.989+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_news', 'extract_and_save_task', 'manual__2025-02-06T11:39:18.448534+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/extract_dag.py', '--cfg-path', '/tmp/tmp15q388e_']
[2025-02-06T11:39:20.990+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask extract_and_save_task
[2025-02-06T11:39:21.035+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_news.extract_and_save_task manual__2025-02-06T11:39:18.448534+00:00 [running]> on host aeb3e4fd1105
[2025-02-06T11:39:21.343+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_news' AIRFLOW_CTX_TASK_ID='extract_and_save_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-06T11:39:18.448534+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-06T11:39:18.448534+00:00'
[2025-02-06T11:39:21.345+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-06T11:39:21.345+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-06T11:39:21.346+0000] {logging_mixin.py:190} INFO - Current task name:extract_and_save_task state:running start_date:2025-02-06 11:39:20.961481+00:00
[2025-02-06T11:39:21.346+0000] {logging_mixin.py:190} INFO - Dag name:extract_news and current dag run status:running
[2025-02-06T11:39:21.347+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-06T11:39:21.348+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract.py", line 19, in extract_and_save
    reddit = praw.Reddit(
             ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/praw/util/deprecate_args.py", line 46, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/praw/reddit.py", line 259, in __init__
    raise MissingRequiredAttributeException(
praw.exceptions.MissingRequiredAttributeException: Required configuration setting 'client_id' missing. 
This setting can be provided in a praw.ini file, as a keyword argument to the Reddit class constructor, or as an environment variable.
[2025-02-06T11:39:21.364+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-06T11:39:21.364+0000] {logging_mixin.py:190} INFO - Task start:2025-02-06 11:39:20.961481+00:00 end:2025-02-06 11:39:21.363648+00:00 duration:0.402167
[2025-02-06T11:39:21.365+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_and_save_task> dag:<DAG: extract_news> dagrun:<DagRun extract_news @ 2025-02-06 11:39:18.448534+00:00: manual__2025-02-06T11:39:18.448534+00:00, state:running, queued_at: 2025-02-06 11:39:18.464132+00:00. externally triggered: True>
[2025-02-06T11:39:21.365+0000] {logging_mixin.py:190} INFO - Failure caused by Required configuration setting 'client_id' missing. 
This setting can be provided in a praw.ini file, as a keyword argument to the Reddit class constructor, or as an environment variable.
[2025-02-06T11:39:21.366+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_news, task_id=extract_and_save_task, run_id=manual__2025-02-06T11:39:18.448534+00:00, execution_date=20250206T113918, start_date=20250206T113920, end_date=20250206T113921
[2025-02-06T11:39:21.379+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-06T11:39:21.380+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 9 for task extract_and_save_task (Required configuration setting 'client_id' missing. 
This setting can be provided in a praw.ini file, as a keyword argument to the Reddit class constructor, or as an environment variable.; 79)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract.py", line 19, in extract_and_save
    reddit = praw.Reddit(
             ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/praw/util/deprecate_args.py", line 46, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/praw/reddit.py", line 259, in __init__
    raise MissingRequiredAttributeException(
praw.exceptions.MissingRequiredAttributeException: Required configuration setting 'client_id' missing. 
This setting can be provided in a praw.ini file, as a keyword argument to the Reddit class constructor, or as an environment variable.
[2025-02-06T11:39:21.404+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-06T11:39:21.586+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-06T11:39:21.594+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
